version: "3.6"

services:
    db:
        image: mariadb
        restart: always
        environment:
             - MYSQL_ROOT_PASSWORD=testdb
        volumes:
            - ./db:/var/lib/mysql
        command: --innodb-flush-method=fsync     
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
